### ISSUE TITLE
Pipeline doesn't run for some contributors (non Capgemini Team members)

### ISSUE THREAD

**Issue by Zwuai** [Capgemini/powerapps-specflow-bindings#101]
## Describe the bug
PRs for Dependabot and Jams-H don't trigger the required pipeline checks, which means their PRs can never be merged.

## To reproduce
I believe this is reproducible by creating a PR as a user who is not part of the Cap team.

## Expected behaviour
Non Cap team users should be able to create completable PRs that have the required checks completed.

**Comment by ewingjm** [comment]
Hi, @Zwuai. I think this is expected behaviour - it's potentially risky to run pipelines automatically for non-team members as the pipeline uses their version of the pipeline YAML and we can't guarantee that they haven't added anything malicious. The best we can do here is make sure that everyone that should be in the team is in the team or have a team member trigger the pipeline manually with the comment trigger `/AzurePipelines run`
